version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/transactions
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  seed:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["node", "seeds/seedTransactions.js"]
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/transactions

volumes:
  mongo-data:
